class_name: "agents.twenty_fourty_eight.gemini_twenty_fourty_eight.GeminiTwentyFourtyEightAgent"
model: gemini-3-flash-preview
temperature: 1.0
gcp_location: "global"
thinking_level: "high"
track: "TRACK2" 
