env_name: "PokemonRed"
log_path: ./logs
task: DefeatBrock
input_modality: "text"
rom_path: ./executables/pokemon_red/pyboy/pokered.gbc
success_condition: get_boulder_badge
max_episodes: 3
max_steps: 200
