# @package _global_

## Config for running application and graph locally in dev mode with docker-compose

ENV: ${oc.env:ENV, "dev"}
CWD: ${hydra:runtime.cwd}
LOG_LEVEL: ${oc.env:LOG_LEVEL, "DEBUG"}

defaults:
  - _self_
  - twenty_fourty_eight: base
  - override twenty_fourty_eight/agent: gemini
